### ISSUE TITLE
Unable to customize default handlers in Story

### ISSUE THREAD

**Issue by jpzwarte** [mswjs/msw-storybook-addon#105]
```ts
export default {
  title: 'Example',
  parameters: {
    msw: {
      handlers: [
        rest.get('/foo', ....),
        rest.get('/bar', ....),
      ]
    }
} satisfies Meta<Props>;

type Story = StoryObj<Props>;

export const Story: Story = {
  parameters: {
    msw: {
      handlers: [
        // Overwrite or add a handler here; you lose the /bar handler here
        rest.get('/foo', ....)
      ]
    }
  }
};
```

So in the "Story" story, you lose the `/bar` handler. My expectation was that I could add or overwrite any default handlers in a story.

**Comment by jpzwarte** [comment]
RTFM: https://github.com/mswjs/msw-storybook-addon#composing-request-handlers

**Comment by awreese** [comment]
I guess the piece that was unclear and tripped me up for a while is the fact that ***all*** `parameters.msw.handlers` need to be objects with keys in order for inheritance to work as expected, in the default exports ***and*** in individual stories. The [Composing request handlers](https://github.com/mswjs/msw-storybook-addon#composing-request-handlers) doesn't explicitly state this is the case. Of course in hind site this totally makes sense now.

@yannbf I created #158 to address this in the README and hopefully make this clearer for the next dev.
