### ISSUE TITLE
Possible issue when used with build-storybook

### ISSUE THREAD

**Issue by jasonfry** [mswjs/msw-storybook-addon#106]
Hi,

I encountered an issue when using `build-storybook` script and then copying over the `storybook-static` directory that gets created over to [gitlab pages ](https://docs.gitlab.com/ee/user/project/pages/). We use gitlab pages to host our internal storybooks.

Inside one of the iframe bundles is `var DEFAULT_START_OPTIONS={serviceWorker:{url:"/mockServiceWorker.js",options:null}`

The problem: But that leading forward slash causes it to look for  the `mockServiceWorker.js` at root level instead of the where it actually is which is the directory where I moved the `storybook-static` directory, which is inside a storybook directory inside the actual project directory on gitlab. So it doesn't load and MSW therefore doesn't work.

I have no idea where this gets bundled, maybe it's the responsibility of Storybook itself? And I also have no idea if the slash is there for a reason, but I remove it via a find and replace script in the CI before moving it to its final location and everything seems to work okay.

Thanks for your time,
Jason.

**Comment by richardtagger** [comment]
You can pass start options to override the default. If you use ./ it'll use the current directory.

```js
initializeMsw({
  serviceWorker: {
    url: './mockServiceWorker.js',
  },
});
```

**Comment by jasonfry** [comment]
Thanks!
