### ISSUE TITLE
Do not know how I can mock my RTK websocket with this lib

### ISSUE THREAD

**Issue by kasir-barati** [mswjs/msw-storybook-addon#129]
Hi dear reader

I was looking at this lib and could not find any clue on how you should mock your WebSocket when you are using a library like Redux and SocketIO. Let's say you have a RTK query like this:
```ts
endpoints: (build) => ({
  someSubscription: build.query<ResponseSchema[], void>({
    queryFn: async () => {
      return { data: null }
    },
    async onCacheEntryAdded(_, { updateCachedData, cacheDataLoaded, cacheEntryRemoved }) {
      const socket = io('ws://localhost:3000/', {
        withCredentials: true,
        transports: ['websocket'],
      })
      socket.on("message", () => {/* cache received msg in */})
      socket.close()
    },
  }),
})
```

How can I mock the cached data? is it even possible to do it with this lib? if not with what I can do that?

**Comment by kasir-barati** [comment]
I think we need to leverage and utilise two things at the same time, the first one I think is this addon and the other one might be: https://github.com/thoov/mock-socket

After a few weeks I ended up asking same question and landing back to this page again but not luck still 😭

**Comment by yannbf** [comment]
Hey there! MSW didn't support mocking web sockets before but it seems like [it does now](https://github.com/mswjs/msw/discussions/2010)! If you're willing to make a contribution to this repo with a reasonable, simple websocket example, we can try to set mocks for it and it can serve as reference for others!

cc @kettanaito

**Comment by kettanaito** [comment]
Second what @yannbf is saying here! We are bringing a first-class WebSocket support to MSW, which is already available in a public beta. 

```sh
npm i msw@next
```

- Learn how to use: https://website-git-docs-ws-mswjs.vercel.app/docs/basics/handling-websocket-events
- Share feedback: https://github.com/mswjs/msw/discussions/2010

I've got a few [usage](https://github.com/mswjs/examples/pull/103) [examples](https://github.com/mswjs/examples/pull/110) as well, feel free to reference those.

**Comment by kettanaito** [comment]
MSW supports mocking WebSockets since `msw@2.6.0`. 

- [Docs: Handling WebSocket events](https://mswjs.io/docs/basics/handling-websocket-events)

Minimal usage example:

```js
import { ws } from 'msw'

const chat = ws.link('wss://api.example.com/chat')

export const YourStory = {
  parameters: {
    msw: {
      handlers: [
        chat.addEventListener('connection', ({ client }) => {
          client.send('Hello from mock!')
        })
      ]
    }
  }
}
```
