### ISSUE TITLE
Can not able to import msw-storybook-addon

### ISSUE THREAD

**Issue by akib22** [mswjs/msw-storybook-addon#130]
I tried to mock api call using msw-storybook-addon. When I tried to configure this package in `preview.js`, I got this error(image below).

![Screenshot 2023-12-12 at 6 47 01 PM](https://github.com/mswjs/msw-storybook-addon/assets/48094649/ebb9b49e-0727-4641-81cb-eb6a0cea27b5)

```js
// preview.js

import { initialize, mswLoader } from "msw-storybook-addon"

initialize()

const preview = {
    parameters: {
        actions: { argTypesRegex: "^on[A-Z].*" },
    },
    loaders: [mswLoader]
}

export default preview
```

Node: v18.17.1 
Packages:
- "vite": "^5.0.8"
- "msw": "^2.0.11"
- "msw-storybook-addon": "^1.10.0"
- "@storybook/addon-actions": "^7.5.3"
-  "@storybook/addon-essentials": "7.0.18"
- "@storybook/preview-api": "^7.5.3"
- "@storybook/react-vite": "7.0.18"

**Comment by FrankvanZ** [comment]
this issue is already being tracked AFAIK here:
https://github.com/mswjs/msw-storybook-addon/issues/121
and here:
https://github.com/mswjs/msw-storybook-addon/pull/122

**Comment by kettanaito** [comment]
Hi. I believe this has been resolved. If you still experience this issue, please submit it again, providing a reproduction repository with the latest versions of the tools. Thanks.
