### ISSUE TITLE
Breaks on building Storybook

### ISSUE THREAD

**Issue by XiNiHa** [mswjs/msw-storybook-addon#131]
While building the Storybook, the bundler (Vite) emits an error like this:

```
[commonjs--resolver] No known conditions for "./native" specifier in "msw" package
```

This is because of [the code here](https://github.com/mswjs/msw-storybook-addon/blob/0ff898a0272df0a6eeebe9faa09b3690509a8b53/packages/msw-addon/src/mswDecorator.ts#L28-L32). While it'll work without any problem when not built, this will break on browser builds because...

- The bundler doesn't know whether `IS_REACT_NATIVE` is true or false at build time, therefore it should try to bundle both versions.
- However, since the bundler is building for browsers and that enables the `browser` export condition, [the entry resolves to null](https://github.com/mswjs/msw/blob/ea28bd9ad2efe0918660cd37054f21883caa3d30/package.json#L31) and it errors.

This problem should be fixed by adding separate entries for each browser and native.

**Comment by belandrio** [comment]
I am facing the same issue

**Comment by YouHusam** [comment]
I am having the same issue, are there any workarounds?

**Comment by demmyhonore** [comment]
Same here, using framework: `@storybook/react-vite`. Any workaround would be appreciated.

**Comment by CHE1RON** [comment]
Same here. Canary works, although I receive warnings about requests "without a matching request handler":

![image](https://github.com/mswjs/msw-storybook-addon/assets/122524301/716f969b-9358-4fa0-b9e5-8d32daed96ee)

**Comment by satoshi-izawa** [comment]
I faced the same problem
`node_modules/vite/node_modules/esbuild/lib/main.js:1374:21: ERROR: [plugin: vite:dep-pre-bundle] No known conditions for "./native" specifier in "msw" package`

msw-storybook-addon: `2.0.0-beta.0`
msw: `2.0.13`
vite: `5.0.11`

**Comment by jetzhliu** [comment]
npm i --save-dev msw@^1
ref: https://github.com/mswjs/msw-storybook-addon/blob/main/packages/msw-addon/package.json#L45

**Comment by marksulls** [comment]
Similar to the _Vite_ specific fix above, this _Webpack_ configuration is working for me (Angular / Storybook / Nx workspace):

in _.storybook/main.ts_:

`import { StorybookConfig } from "@storybook/angular";
import * as path from "path";

const config: StorybookConfig = {
  stories: ['../**/*.stories.@(js|jsx|ts|tsx|mdx)'],
  addons: [
    '@storybook/addon-interactions',
    '@storybook/addon-docs',
    '@storybook/addon-essentials',
  ],
  framework: {
    name: '@storybook/angular',
    options: {},
  },
  staticDirs: ['../src/lib/msw'],
  // webpack workaround see https://github.com/mswjs/msw-storybook-addon/issues/131#issuecomment-1887930180
  webpackFinal: async (config) => {
    if (config.resolve) {
      config.resolve.alias = {
        ...config.resolve.alias,
        'msw/native': require.resolve(
          path.resolve(__dirname, '../../../node_modules/msw/lib/native/index.mjs')
        )
      };
    }
    return config;
  }
};`


```
"msw": "2.1.3",
"msw-storybook-addon": "2.0.0-beta.0",
```

**Comment by henrybravos** [comment]
worked for me:
//vite conf
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { createRequire } from "node:module";
import path from "path";
const require = createRequire(import.meta.url);

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      "msw/native": require.resolve(
        path.resolve(__dirname, "./node_modules/msw/lib/native/index.mjs")
      ),
    },
  },
});

**Comment by yannbf** [comment]
Hey everyone! If you're using MSW 2.0.0, we just released a new beta version that should have fixed this issue: `msw-storybook-addon@2.0.0-beta.1`.

Would you please try it out and let us know? Thank you!
cc @satoshi-izawa @marksulls tagging you since I know you're using msw 2!

**Comment by bmulholland** [comment]
For those who try it out, be very careful with your version specification in package.json. There's a "next" version of 2.0.0, `2.0.0-next.1`, that is 9 months old -- but e.g. a version pin of `>= 2.0.0-beta.1` will select that one. I suggest double checking your lockfile to see exactly what version you end up with.

**Comment by bmulholland** [comment]
Confirmed that the beta solves this issue for me 🎉

**Comment by magus** [comment]
The types aren't correct for the `2.0.0-beta1` but everything else works otherwise!

**Comment by chapmanio** [comment]
I've followed the vite-specific instructions here but I'm now getting this error:

> [ERROR] No known conditions for "./node" specifier in "msw" package [plugin vite:dep-pre-bundle]

Is anyone having anything similar?

```ts
viteFinal: (config) => {
    config.resolve = {
      ...config.resolve,
      alias: {
        ...config.resolve?.alias,
        ["msw/native"]: require.resolve("../node_modules/msw/lib/native/index.mjs"),
      },
    };

    return mergeConfig(config, {
      plugins: [tsconfigPaths()],
    });
  },
```

```ts
    "msw": "^2.1.6",
    "msw-storybook-addon": "^2.0.0-beta.1",
```

**Comment by aronchick** [comment]
@chapmanio i solved that because you're using "msw/node" in something that is client code only. You may need to swap to "msw/browser" (but this will prevent you from using server libraries like fs or path).

**Comment by chapmanio** [comment]
> @chapmanio i solved that because you're using "msw/node" in something that is client code only. You may need to swap to "msw/browser" (but this will prevent you from using server libraries like fs or path).

Do you have a code example of how to do that?  I'm not importing MSW in my code (I assume that is being done by `msw-storybook-addon`) so it's not clear how to change this.

**Comment by glodynator** [comment]
> I've followed the vite-specific instructions here but I'm now getting this error:
> 
> > [ERROR] No known conditions for "./node" specifier in "msw" package [plugin vite:dep-pre-bundle]
> 
> Is anyone having anything similar?
> 
> ```ts
> viteFinal: (config) => {
>     config.resolve = {
>       ...config.resolve,
>       alias: {
>         ...config.resolve?.alias,
>         ["msw/native"]: require.resolve("../node_modules/msw/lib/native/index.mjs"),
>       },
>     };
> 
>     return mergeConfig(config, {
>       plugins: [tsconfigPaths()],
>     });
>   },
> ```
> 
> ```ts
>     "msw": "^2.1.6",
>     "msw-storybook-addon": "^2.0.0-beta.1",
> ```

I'm having the same issue.

**Comment by acc-nicholas** [comment]
I'm having a similar issue: `[vite] Internal server error: No known conditions for "./node" specifier in "msw" package`

This works:

```
import { handlers } from "../mocks/handlers";

// Initialize MSW
initialize(
  {
    onUnhandledRequest: "warn",
  },
  [...handlers],
);
```

This does not work when importing from another lib in my monorepo.

```
import { handlers } from "@otherlib/mocks";

// Initialize MSW
initialize(
  {
    onUnhandledRequest: "warn",
  },
  [...handlers],
);
```

I have proper vite/typescript aliases/paths set up for this mocks lib btw.


```
"msw": "^2.2.1",
"msw-storybook-addon": "^2.0.0-beta.1",
```

**Comment by yannbf** [comment]
Hey everyone! Finally the major version is out. Sorry for such a long wait, I had to make sure the addon aligned with Storybook 8 and worked correctly in the portable stories (using stories in Vitest,Jest) scenario.

Please check the release notes, try it out and provide feedback in case issues arise:
https://github.com/mswjs/msw-storybook-addon/releases/tag/v2.0.0

Thanks!

**Comment by rjaguilar** [comment]
I'm still getting this issue 

[vite] Internal server error: No known conditions for "./node" specifier in "msw" package

"msw-storybook-addon": "2.0.3",
"msw": "2.4.3"

what is the solution for this ?

**Comment by yannbf** [comment]
> I'm still getting this issue
> 
> [vite] Internal server error: No known conditions for "./node" specifier in "msw" package
> 
> "msw-storybook-addon": "2.0.3", "msw": "2.4.3"
> 
> even while following
> 
> ```
> // .storybook/preview.js
> -import { initialize, mswDecorator } from 'msw-storybook-addon'
> +import { initialize, mswLoader } from 'msw-storybook-addon'
> 
> initialize()
> 
> const preview = {
> -  decorators: [mswDecorator]
> +  loaders: [mswLoader]
> }
> 
> export default preview
> ```
> 
> what is the solution for this ?

That's quite odd! Could this be your node version? Could you check whether you have multiple MSW versions installed in your project? e.g. `yarn why msw`

**Comment by todor-a** [comment]
Still getting this with:
- vite - 6.3.4
- storybook - 8.6.12
- msw - 2.7.6
- msw-storybook-addon - 2.0.4

```

  ✘ [ERROR] No known conditions for "./node" specifier in "msw" package [plugin vite:dep-scan]

    src/test-utils/msw/mocks/server.ts:1:28:
      1 │ import { setupServer } from 'msw/node';
        ╵                             ~~~~~~~~~~

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1137:20:
      1137 │       let promise = setup({
           ╵                     ^

    at setup (file:///my-app/node_modules/vite/dist/node/chunks/dep-Bn81Esdm.js:14478:13)
    at handlePlugins (/my-app/node_modules/esbuild/lib/main.js:1137:21)
    at buildOrContextImpl (/my-app/node_modules/esbuild/lib/main.js:852:5)
    at Object.buildOrContext (/my-app/node_modules/esbuild/lib/main.js:678:5)
    at /my-app/node_modules/esbuild/lib/main.js:2030:68
    at new Promise (<anonymous>)
    at Object.context (/my-app/node_modules/esbuild/lib/main.js:2030:27)
    at Object.context (/my-app/node_modules/esbuild/lib/main.js:1872:58)
    at prepareEsbuildScanner (file:///my-app/node_modules/vite/dist/node/chunks/dep-Bn81Esdm.js:14266:24)


    at failureErrorWithLog (/my-app/node_modules/esbuild/lib/main.js:1463:15)
    at /my-app/node_modules/esbuild/lib/main.js:924:25
    at runOnEndCallbacks (/my-app/node_modules/esbuild/lib/main.js:1303:45)
    at buildResponseToResult (/my-app/node_modules/esbuild/lib/main.js:922:7)
    at /my-app/node_modules/esbuild/lib/main.js:934:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (/my-app/node_modules/esbuild/lib/main.js:933:54)
    at handleRequest (/my-app/node_modules/esbuild/lib/main.js:626:17)
    at handleIncomingPacket (/my-app/node_modules/esbuild/lib/main.js:651:7)
    at Socket.readFromStdout (/my-app/node_modules/esbuild/lib/main.js:579:7)
```
