### ISSUE TITLE
Quick question on this library

### ISSUE THREAD

**Issue by alexbjorlig** [mswjs/msw-storybook-addon#132]
I'm pretty new to Storybook and `msw`. I tried setting up this library in a story, and some things seem to work.

I then try to read the documentation [here](https://mswjs.io/docs/concepts/request-handler) - where there is talked extensively about importing `HttpResponse` from `'msw'`. But when I try this in my story, I just get: 

```
import { rest, HttpResponse  } from 'msw';
// '"msw"' has no exported member named 'HttpResponse'. Did you mean 'response'?ts(2724)
```

I'm I reading documentation the wrong place, or what is up and down here?

**Comment by dorisli99** [comment]
Hi @alexbjorlig , were you able to resolve this? I ran into the same error. Thanks!

**Comment by yannbf** [comment]
Hey there @alexbjorlig @dorisli99! This library's stable release does not support MSW 2, which is what you're trying to use.
We have a canary version which does support it, so please try that out:
https://github.com/mswjs/msw-storybook-addon/pull/122#issuecomment-1975962125

The idea is to make a new stable release soon, which will support MSW 2!
