### ISSUE TITLE
Cannot read properties of undefined (reading 'apply')

### ISSUE THREAD

**Issue by aronchick** [mswjs/msw-storybook-addon#139]
I filed this on StackOverflow and they redirected me here (https://stackoverflow.com/questions/77985046/why-is-storybook-throwing-this-undefined-apply-error?noredirect=1#comment137483137_77985046)

---- 
If I remove the "initialize" in the middle, it works ... sort of. It fails with some other errors around Configure.mdx. So I followed the instructions[1] and I get the errors below. I can't quite figure out what I'm missing!

Here is the error:
```
Cannot read properties of undefined (reading 'apply')
```

Here is my preview.tsx:
```
import type { Preview } from "@storybook/react"
import {
  reactRouterParameters,
  withRouter,
} from "storybook-addon-react-router-v6"
import "../src/index.scss"
import { passthrough } from "msw"
import { setupWorker } from "msw/browser"
import { initialize, mswDecorator } from 'msw-storybook-addon';
import { handlers as storyBookHandlers } from "../.storybook/storybookHandlers"

const handlers = []

initialize({
  onUnhandledRequest: ({ method, url }) => {
    console.info(`Full: ${method} ${url}`)
    if (!url.includes("/api")) {
      console.info(`Passthrough: ${method} ${url}`)
      return passthrough();
    }
  },
}, storyBookHandlers)

const preview: Preview = {
  // decorators: [(storyFn, context) => withConsole()(storyFn)(context)],
  parameters: {
    actions: { argTypesRegex: "^on[A-Z].*" },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
  },
}

if (typeof global.process === "undefined") {
  const { worker } = require("../tests/mocks/browser")
  worker.start()
}

export default {
  decorators: [withRouter],
  parameters: {
    reactRouter: reactRouterParameters({}),
  },
} satisfies Preview
```

Any thoughts? 

[1] https://github.com/mswjs/msw-storybook-addon#configuring-msw

**Comment by aronchick** [comment]
I don't mean to bother (I know it's open source) but i'm pretty stuck here. Is there a direction I should investigate?

**Comment by ibrykov-mdsol** [comment]
It looks like `msw-storybook-addon` is not compatible with the latest major version of `msw`. I tried it with version 1.3.2 and it worked just fine.

**Comment by ilovett** [comment]
@aronchick following some of the other issues it looks like there is a beta `msw-storybook-addon`  and some users claiming it works great https://github.com/mswjs/msw-storybook-addon/issues/121

**Comment by aronchick** [comment]
It was just this - i couldn't figure it out. I took it out, and am now just using MSW service worker directly.
