### ISSUE TITLE
Storybook build is broken with 2.0 beta version

### ISSUE THREAD

**Issue by BortsovaSvetlana** [mswjs/msw-storybook-addon#142]
Hey everyone! 
I get an error with `msw-storybook-addon@2.0.0-beta.1` version, but storybook works fine with canary version `2.0.0--canary.122.b3ed3b1.0`. I changed only version and got broken build. Does anyone have an idea why it happens? I use `"msw": "2.2.1"`

<img width="1075" alt="image" src="https://github.com/mswjs/msw-storybook-addon/assets/44258529/2475bdb9-b90d-4aee-863f-1ea4f5292c71">

**Comment by yannbf** [comment]
Hey everyone! Finally the major version is out. Sorry for such a long wait, I had to make sure the addon aligned with Storybook 8 and worked correctly in the portable stories (using stories in Vitest,Jest) scenario.

Please check the release notes, try it out and provide feedback in case issues arise:
https://github.com/mswjs/msw-storybook-addon/releases/tag/v2.0.0

Thanks!
