### ISSUE TITLE
MSW version 2.4.1 breaks msw in portable stories

### ISSUE THREAD

**Issue by tmeindle** [mswjs/msw-storybook-addon#162]
When updating my msw to versions greater than 2.4.0  msw-storybook-addon stops functioning in portable stories rendered in tests in vitest (and react swc plugin).  

Using latest versions of storybook, vitest, and storybook.

Msw 2.4.1 added a peer dependency on graphql in a patch version update.  Adding a peer dependency is usually introduces breaking changes.

**Comment by kettanaito** [comment]
Hi. The change that added `graphql` as a optional peer dependency has been reverted. Update `msw` to get the changes. 

Introducing optional peer dependencies is not a breaking change—that's the whole point of them being optional. Sadly, there isn't a proper protocol to achieve optional peer dependencies in JavaScript as of now, especially across multiple module formats.
