### ISSUE TITLE
Also ignore prettier

### ISSUE THREAD

**Issue by binarykitchen** [mswjs/msw-storybook-addon#163]
At the top of the `mockServiceWorker.js` you have 

```
/* eslint-disable */
/* tslint:disable */
```

Which is a great idea. I would also add prettier ignore here.

**Comment by yannbf** [comment]
Hey there @binarykitchen I appreciate the feedback. This repo is for the MSW addon, your feedback is related to the content of MSW. I'd suggest you to request this in the MSW repo instead. Thanks!
