### ISSUE TITLE
How should this work with vue3

### ISSUE THREAD

**Issue by MatthijsBe** [mswjs/msw-storybook-addon#20]
Hi, 

I've a question regarding this addon and vue + graphql,  on the storybook addon page Vue is under "works with".

So I'm trying to add this to my story, in the example I only see React stories, those work with story Parameters. 

Vue stories will work with Args, but when I add msw :[ query here] to my args, I will get the following error in my console:

![image](https://user-images.githubusercontent.com/31308832/110769760-d8be1180-8258-11eb-8194-6c30601dbec6.png)

MSW is succesfully loaded becasue I see: _[MSW] Mocking enabled._ in my console.

Any insights on how to get this working with Vue(3) + graphql?

**Comment by itaditya** [comment]
I haven't worked with Vue 3 before. From Storybook docs, it looks like story parameters are supported there also. Have you tried it? Currently my addon doesn't work with args

https://storybook.js.org/docs/vue/writing-stories/parameters

**Comment by kettanaito** [comment]
Hey, @MatthijsBe. Could you please share your request handlers? (`graphql.query(...)`). Looks like you have a dynamic part in an endpoint that resolves to `undefined` on runtime.

**Comment by kettanaito** [comment]
This addon, as well as MSW (underlying API mocking library), do not have any framework/library-specific logic. In other words, they work with any setup of your choice, as long as that setup produces valid HTTP requests. Based on the little info provided above, I can see that the request URL is invalid, as it includes `undefined` in it. This is very likely an issue on your side (i.e. a misplaced environmental variable). 

If you wish us to investigate the issue further, please prepare a reproduction repository where we can observe this error reliably when running this addon in Storybook.
