### ISSUE TITLE
Add support for node environments

### ISSUE THREAD

**Issue by yannbf** [mswjs/msw-storybook-addon#26]
Storybook is awesome, and so is msw. I wrote [@storybook/testing-react](https://github.com/storybookjs/testing-react#readme) to allow users to completely reuse stories in tests, so that people don't need to create similar setups twice.
The library has incredible potential to work very efficiently with this addon, as long as it somehow supports non-browser environments. I have tweaked slightly with it and it has worked perfectly.

This is the change:
```js
export function initializeWorker(options) {
  if (typeof global.process === 'undefined') {
    worker = setupWorker();
    worker.start(options);
  } else if (maybeSomeFlagHere) {
    worker = setupServer();
    worker.listen(options);
  }
}
```

After talking to @kettanaito, I am enthusiastic to bring a PR with the changes, as well as making more improvements to this addon. I'm wondering if the fallback to node support should be opt-in, opt-out or just default. 

What are your thoughts on all of this? :D

**Comment by kettanaito** [comment]
Hey, @yannbf. Thank you for putting this proposal down.

I think it's a good move forward, and I think we should give the Node.js support a try. It may get tricky deciding when Storybook is running in Node.js, but we can get to it during the collaboration on the pull request. Huge thanks for preparing that, by the way!

**Comment by beaussan** [comment]
Hi, I see that the pr is merged, do you have a time window for a new release of this addon that have this feature ?

Thanks !

**Comment by yannbf** [comment]
@kettanaito @itaditya would you be able to release a new version?

**Comment by kettanaito** [comment]
Hey, @beaussan, @yannbf. I don't think I have the necessary rights to publish this package to NPM. 

@itaditya, could you please release the next minor version of the add-on?

**Comment by yannbf** [comment]
@itaditya would it be possible to setup an automated release process for the repo? We can use [auto](https://www.npmjs.com/package/auto) which makes things really really simple. Then we can move faster, and finally close a few issues in this repo 💃

**Comment by winkerVSbecks** [comment]
@itaditya any chance you could release this in the next couple of days? I'm working on a new post about interaction testing and would love to recommend the MSW addon as the preferred method for mocking.

**Comment by kettanaito** [comment]
I've reached out to @itaditya and hope to get this matter resolved sometime this week. Thank you for your patience.

**Comment by kettanaito** [comment]
`msw-storybook-addon@1.2.0` has been successfully published (see [release notes](https://github.com/mswjs/msw-storybook-addon/releases/tag/v1.2.0)). 

@yannbf, should we close this issue?

**Comment by yannbf** [comment]
Hey @kettanaito that news warms my heart <3
I just tested out in my project and it's just

<img src="https://i.kym-cdn.com/photos/images/newsfeed/001/168/676/09e.gif" />


1 - Deprecation notice to use `initialize` method instead of `initializeWorker`
2 - Tests work wonderfully and beautifully in node

@winkerVSbecks @beaussan time to try this out 🎉 


Closing the issue now! Thanks a lot for this journey @kettanaito!
