### ISSUE TITLE
Passing msw returned resuts into specific storybook component args

### ISSUE THREAD

**Issue by BennaceurHichem** [mswjs/msw-storybook-addon#35]
I'm trying to pass the result of the MSW request added in parameters to a specific story component arg, the approach described in all examples shown in the doc is passing the endpoint URL as props into the component, then the component treats the result. In my case, I want to pass the result of the MSW request into the story component as props via args, which means that the data will be ready for the component directly when the fetching from MSW is finished. How can I pass the MSW returned data directly into args in the story component? I'm using Nuxt.js and Nuxt-storybook module.

**Comment by yannbf** [comment]
Hey @BennaceurHichem, thanks for using this addon!

I'm trying to understand your use case, but I'm a bit confused. MSW is reactive, so it will only proxy requests once they are done, and then intercept the request and manipulate its response. It's very handy when you want to manipulate data that is not readily available.

It seems like you want your component's args to _already_ have the data. If you want the data to be passed via args, then you should just pass the mock data directly to args, without even using the addon:

```js
export const UserList = Template.bind({});
UserList.args = {
  data: someMockedData,
};
```

Could you elaborate a bit more? I might have misunderstood you.

**Comment by yannbf** [comment]
Hey @BennaceurHichem sorry but it's been quite some time and we haven't had an answer with more info. I'll close this issue if you don't mind. Feel free to open it again in case you have more information that could help us help you out!

Once again, thanks for using this library!
