### ISSUE TITLE
Add Typescript declaration file

### ISSUE THREAD

**Issue by tyankatsu0105** [mswjs/msw-storybook-addon#38]
Storybook supports config files with TS if installed `ts-node`.
If exist a declaration file, TS users can use `initializeWorker` and `mswDecorator` when using `preview.ts`.

**Comment by kettanaito** [comment]
Hey, @tyankatsu0105.

We are planning on improving this add-on, which includes rewriting it to TypeScript to come with the type definitions by default. I'll let you know once that work is complete.

**Comment by tyankatsu0105** [comment]
Cool! Thanks @kettanaito :)
So, should I close PR for this issue?

**Comment by aurbano** [comment]
Any update on this?

**Comment by yannbf** [comment]
Hey everyone, sorry for such a long wait. There is currently an open PR to fix this. 
Thanks for your patience!
