### ISSUE TITLE
Getting global is not defined error

### ISSUE THREAD

**Issue by Secretmapper** [mswjs/msw-storybook-addon#42]
Whenever using msw-storybook-addon, I get a global is not defined error.

The fact that I'm using [Storybook for Vite](https://storybook.js.org/blog/storybook-for-vite/) might be related

**Comment by Secretmapper** [comment]
Removing server side rendering support (ie, removing `global` variable, IS_BROWSER else) makes msw work.

Probably because Storybook for vite doesn't use babel(?) and so preset-env doesn't get loaded

**Comment by brettdewoody** [comment]
Where did you remove SSR support to make this work?

**Comment by kettanaito** [comment]
This should be resolved in #41. Please wait for the next add-on release. Thank you.
