### ISSUE TITLE
Enable default handlers to be specified

### ISSUE THREAD

**Issue by MattCarr147** [mswjs/msw-storybook-addon#46]
I've recently started using MSW and I have some 'default' Mock API handlers defined under a 'mocks' directory which I use with MSW during development (when the API endpoints aren't in place, etc). 

Unless I'm testing a particular request scenario (e.g. a loading state, error state), I'd ideally want these default handlers to be used by stories/tests. I plan to use msw-storybook-addon for defining scenario-specific network/response behaviour. 

The addon is working great for the latter, but I can't see a way to specify the default handlers as 'setupWorker' is called within msw-storybook-addon without any parameters. Am I missing something? Is there a reason to avoid the idea of default handlers? 

Cheers

**Comment by dominictwlee** [comment]
I think you can do this in your `.storybook/preview.js`

```
export const parameters = {
  msw: [], // pass in your handlers here
};
```

**Comment by MattCarr147** [comment]
Thanks @dominictwlee, that's the solution I opted for in the end too and seems to be working for my needs so far. Cheers for the heads up about the gotcha in #43 though, was unware of that.

I'll close this one for now and keep an eye on #43 👍
