### ISSUE TITLE
Readme discrepency

### ISSUE THREAD

**Issue by ketain** [mswjs/msw-storybook-addon#57]
I have recently started to use the `mws-storybook-addon` but but found the following discrepency between the docs and the actual code and was wondering what the supposed correct variant is supposed to be.

| Package Name  | Version  |
|---|---|
|  msw |  0.35.0  |
|  mws-storybook-addon  |  1.4.1  |
|  storybook-react  |  6.3.12  |

On the official [npm](https://www.npmjs.com/package/msw-storybook-addon) page the in-story configuration looks like this:
![image](https://user-images.githubusercontent.com/9215393/141976272-49679719-424e-463d-8702-030b8d41b362.png)

In this repo it looks like this:
![image](https://user-images.githubusercontent.com/9215393/141976429-3928124f-bc23-4d1c-a127-40d56dd04603.png)

When debugging, the actual code on my machine it looks like this:
![image](https://user-images.githubusercontent.com/9215393/141976637-a510a4dd-d17b-4e81-92df-5c490d2b0f68.png)

So the variant which actually works is the first one. But the latter variant looks as if it was the intended improvement over the first design.

**Comment by shanesveller** [comment]
The README was updated simultaneously with the behavior but those changes are in a commit that's not part of a tagged release at the time of writing:

https://github.com/mswjs/msw-storybook-addon/commit/8ad5a6e9190e14735aaef87e074bf4842d57bf5a
The correct README to reference in the meantime is https://github.com/mswjs/msw-storybook-addon/blob/v1.4.1/README.md.

**Comment by yannbf** [comment]
Hey everyone, thanks for notifying! I'm working on updating the docs and making another release so please follow the link from @shanesveller for now. Sorry for the inconvenience!

**Comment by yannbf** [comment]
Hey everyone! Version 1.5.0 has been released and the API is now aligned with what's in the documentation. Thanks for your patience!
