### ISSUE TITLE
Live demos not working?

### ISSUE THREAD

**Issue by HarmonicTons** [mswjs/msw-storybook-addon#66]
Hi,

When accessing https://msw-sb.vercel.app/ none of the demos seem to work. The data displayed in the `Mocked Success` are the actual data, and no error is shown in the `Mocked Error` stories.

A screen capture:

![image](https://user-images.githubusercontent.com/19567391/145418170-fdbd200e-b4d4-4842-a94b-2d9b38a495ce.png)

You can see the API calls being done.

Am I missing something?

Thanks!

**Comment by yannbf** [comment]
Hey @HarmonicTons thanks a lot for catching that! We recently moved the example from netlify to vercel and it seems like the files exported from `public` directory (like public/mockServiceWorker.js) that should be directly accessible in https://msw-sb.vercel.app/mockServiceWorker.js are resulting in a 404. @kettanaito this might just be a config in vercel we are missing?

**Comment by kettanaito** [comment]
Thanks for reporting this. This definitely looks off. 

@yannbf, not sure but it may be. I haven't updated anything recently (don't think I even can). 

There's this runtime error in the console:

```
A bad HTTP response code (404) was received when fetching the script.
```

Unfortunately, it doesn't point to any source or a file reference. I suspect this is an error related to the worker script not being fetched properly. I don't see any request to fetch the worker script in the Network, though. 

Any suggestions on where should I look next?

**Comment by kettanaito** [comment]
Let me check if the worker script is present to the Storybook's output directory after `yarn build`.

**Comment by kettanaito** [comment]
So our Vercel deployment is configured to serve everything under the `packages/docs/storybook-static` directory after the build. The thing is, the worker script is never in that directory after the build. The `public` directory of the NextJS docs project is never respected/copied in any way. You can confirm that yourself by trying to load [robots.txt](https://msw-sb.vercel.app/robots.txt), which is a part of the public directory but never present on the deployed app.

This makes me wonder whether there were any extra steps in the past to copy the worker manually?

**Comment by yannbf** [comment]
> So our Vercel deployment is configured to serve everything under the `packages/docs/storybook-static` directory after the build. The thing is, the worker script is never in that directory after the build. The `public` directory of the NextJS docs project is never respected/copied in any way. You can confirm that yourself by trying to load [robots.txt](https://msw-sb.vercel.app/robots.txt), which is a part of the public directory but never present on the deployed app.
> 
> This makes me wonder whether there were any extra steps in the past to copy the worker manually?

`build-storybook -s./public` would be enough for Storybook to copy the assets over to the built output

**Comment by kettanaito** [comment]
@yannbf, a fantastic mention. It helped me figure out that we were using the wrong command in the root-level `yarn build` for the docs repo.

**Comment by kettanaito** [comment]
The demos are now properly using MSW.
