### ISSUE TITLE
Require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by will-stone** [mswjs/msw-storybook-addon#68]
Hi,

Firstly thank-you for all the hard work on `msw`, it really makes mocking end-points really easy. I have found that on latest Storybook (6.4.9), there's a warning in the console:

```
./node_modules/msw-storybook-addon/dist/mswDecorator.js
25:45-52 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

It is referring to [this line](https://github.com/mswjs/msw-storybook-addon/blob/8eaee90cbbed4cc2768b76122f4f07e0f1b79733/packages/msw-addon/src/mswDecorator.ts#L41). I have found simply commenting it out directly in my node_modules resolves the issue. Is there a reason for assigning `require` to `__non_webpack_require__`? Doesn't this overwrite the point of using `__non_webpack_require__` in this instance? i.e.

1. `globalThis.__non_webpack_require__ = require`
   is replaced by webpack to
   `globalThis.__non_webpack_require__ = __webpack__require__`
2. Meaning the next line reads:
  `const { setupServer } = __webpack_require__('msw/node')`

I'm going to see if I can get this repo up and running in a fork and replicate the issue...

**Comment by will-stone** [comment]
When I installed this project it resolved to Storybook 6.3.8 and the issue was still prevalent, so it's not isolated to just the most recent version. Would you like me to submit this as a PR?

Before:

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/654103/148248970-559bcb9f-0b86-4e0e-9691-e10a381d7ab3.png">

After removing the `globalThis.__non_webpack_require__ = require` line.

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/654103/148248989-a802e8f2-f3fe-4033-8e39-13247ab940e9.png">

**Comment by yannbf** [comment]
Hey @will-stone thanks for opening the issue and doing this investigation! The reason for that code is to support Webpack 5 codebases.

You can check [here](https://github.com/mswjs/msw-storybook-addon/issues/47#issuecomment-939369849) for more context. I'm not sure if there is a better way to support Webpack 5 and remove that warning, I'd love to hear some ideas and I appreciate your efforts!

**Comment by kettanaito** [comment]
It'd be great to find a better way, but the native `require` is stubbed by webpack, causing all sorts of issues when used in our scenario. Escaping that stub produces the warning you're mentioning. 

This is not an issue, however, as static dependency analysis is primarily needed for production build optimization.

**Comment by will-stone** [comment]
Using [the solution that is linked to in the comment](https://github.com/webpack/webpack/issues/8826#issuecomment-660594260) seems to work:

```js
const nodeVer = typeof process !== "undefined" && process.versions?.node;
    const nodeRequire = nodeVer
      ? typeof __webpack_require__ === "function"
        ? __non_webpack_require__
        : require
      : undefined;
```

**Comment by kettanaito** [comment]
That sounds like a great approach, @will-stone. Would you like to open a pull request so we could release it?

**Comment by will-stone** [comment]
Sure @kettanaito, will do 👍 Thanks.
