### ISSUE TITLE
bug: wrong base url

### ISSUE THREAD

**Issue by yuzhanglong** [mswjs/msw-storybook-addon#75]
The default root path doesn't feel very good：
<img width="665" alt="image" src="https://user-images.githubusercontent.com/56540811/157839548-fb7d2fd6-6cca-4199-a510-b2a96f455488.png">

This can cause some problems, and if you don't deploy your site in the root path, the MSW will fail.

**Comment by yuzhanglong** [comment]
Some people have met this problem too：https://github.com/mswjs/msw-storybook-addon/issues/29
<img width="953" alt="image" src="https://user-images.githubusercontent.com/56540811/157839985-70a8c074-cfa3-4e95-8864-5f07aa9d0ea4.png">
cc @KrzychuR

**Comment by kettanaito** [comment]
Hey, @yuzhanglong. 

MSW recommends you always serve the worker from the root path. This way the worker has the highest possible scope, being able to intercept requests regardless of what page in your application is issuing them. That is why the default worker script URL is `/mockServiceWorker.js`, expecting MSW's worker and your app (or Storybook in this case) to be served from the root. 

That being said, there are cases when people don't want (or can't) serve their applications from the root. If that's your case, please tell MSW what is the relative URL to the worker script based on your setup:

```js
// preview.js
import { initialize } from 'msw-storybook-addon';

initialize({
  serviceWorker: {
    url: '/nested/path/mockServiceWorker.js'
  }
})
```

> Learn more about [`setupWorker` options](https://mswjs.io/docs/api/setup-worker/start#serviceworker).

**Comment by yuzhanglong** [comment]
> Hey, @yuzhanglong.
> 
> MSW recommends you always serve the worker from the root path. This way the worker has the highest possible scope, being able to intercept requests regardless of what page in your application is issuing them. That is why the default worker script URL is `/mockServiceWorker.js`, expecting MSW's worker and your app (or Storybook in this case) to be served from the root.
> 
> That being said, there are cases when people don't want (or can't) serve their applications from the root. If that's your case, please tell MSW what is the relative URL to the worker script based on your setup:
> 
> ```js
> // preview.js
> import { initialize } from 'msw-storybook-addon';
> 
> initialize({
>   serviceWorker: {
>     url: '/nested/path/mockServiceWorker.js'
>   }
> })
> ```
> 
> > Learn more about [`setupWorker` options](https://mswjs.io/docs/api/setup-worker/start#serviceworker).
> 
> Note that this option has no effect when running in Node.js and will be ignored.

thank you~

**Comment by kettanaito** [comment]
For posterity, using a custom base URL for your application falls under the [Using custom `homepage` in package.json](https://mswjs.io/docs/getting-started/integrate/browser#using-homepage-property-in-packagejson) notice we have in the documentation.
