### ISSUE TITLE
Allow to initialize the worker with request handlers

### ISSUE THREAD

**Issue by vojty** [mswjs/msw-storybook-addon#88]
I have an array of request handlers that covers all endpoints for the whole app. I use these as default responses in unit tests (so I don't have to constantly define handlers for endpoints like `/notifications` etc) and override them when necessary.
However, I wasn't able to achieve that with this plugin. The overriding & merging of handlers work differently here and it doesn't exactly fit my needs.

What I want is to have an array of default handlers and be able to override specific endpoints in certain stories. I managed to do that with this change:

```ts
// https://github.com/mswjs/msw-storybook-addon/blob/main/packages/msw-addon/src/mswDecorator.ts#L24

export function initialize(options?: InitializeOptions): SetupApi {
  if (IS_BROWSER) {
    const { setupWorker } = require('msw')
    const worker = setupWorker()

-> 

export function initialize(options?: InitializeOptions, requestHanders: RequestHandler[] = []): SetupApi {
  if (IS_BROWSER) {
    const { setupWorker } = require('msw')
    const worker = setupWorker(...requestHanders);

```

I think it's a minor change that doesn't break the API and might be useful for others as well. Shall I create a PR for that or not? What do you think?

**Comment by pentzzsolt** [comment]
This is exactly what I need right now. Both [`setupWorker()`](https://mswjs.io/docs/api/setup-worker) and [`setupServer()`](https://mswjs.io/docs/api/setup-server) support initial request handlers, so you would have to add them to both inside the `initialize` function.

**Comment by jw-miaem** [comment]
would also find this useful right now, any chance of merging?

**Comment by yannbf** [comment]
Hey there! Could you please explain why [composing handlers](https://github.com/mswjs/msw-storybook-addon#composing-request-handlers) would not work in your scenarios?

**Comment by pentzzsolt** [comment]
> Hey there! Could you please explain why [composing handlers](https://github.com/mswjs/msw-storybook-addon#composing-request-handlers) would not work in your scenarios?

Because all our stories use the array syntax and that does not get merged like the object syntax. With the proposed changes, we wouldn't have to update 700+ stories.

**Comment by yannbf** [comment]
> > Hey there! Could you please explain why [composing handlers](https://github.com/mswjs/msw-storybook-addon#composing-request-handlers) would not work in your scenarios?
> 
> Because all our stories use the array syntax and that does not get merged like the object syntax. With the proposed changes, we wouldn't have to update 700+ stories.

Alright that's sound! Let's proceed with your PR <3
