### ISSUE TITLE
Use the new framework API?

### ISSUE THREAD

**Issue by jonniebigodes** [mswjs/msw-storybook-addon#95]
Hey fellow maintainers 👋 !
I'm one of the Storybook maintainers. I focus primarily on documentation and community outreach. I'm opening up this issue and letting you know that the Storybook API for building addons is currently being updated to factor in the changes introduced by the upcoming 7.0 release. If you're interested in making the required changes to help the community from benefiting from using your addon, we've prepared an abridged guide for the required changes [here](https://chromatic-ui.notion.site/Addon-migration-for-Storybook-7-002f2f627c1d470298ca94894ab8a040), and if you have any questions or issues, please reach out to us in the #prerelease channel in our [Discord Server](https://discord.gg/storybook). 

Looking forward to hearing from you and hopefully getting his addon updated as well for 7.0.

Hope everyone has a fantastic day.

Stay safe

**Comment by jpzwarte** [comment]
@jonniebigodes So when using the new `Preview` type, I get this error:
<img width="985" alt="CleanShot 2023-03-03 at 14 47 54@2x" src="https://user-images.githubusercontent.com/3968/222736497-d17b66bf-4c1a-4bd9-85a3-995745f1d5ce.png">

**Comment by jonniebigodes** [comment]
@jpzwarte, thanks for reaching out and providing some context on what's happening with the new Preview types. Appreciate it. I've been talking with the mainatiner, and we will take a look at this soon and have an updated version when humanly possible so that it aligns with the upcoming Storybook 7.0 release. Once it's out, we'll make sure to reference this issue. 

I hope you have a fantastic weekend.

Stay safe

**Comment by kasperpeulen** [comment]
@yannbf I looked at this issue, addon authors will need to use generics to get correct typings for TS 7:

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/1035299/223441948-1d3f8122-5587-4cd9-88b6-cf85e70a98bc.png">

The issue that TS complains about is, that it can not be sure that the return type of the decorator is usable for the specific renderer.  Which is correct, but makes it a bit more verbose.

**Comment by yannbf** [comment]
Hey all! I just made a [1.8.0](https://github.com/mswjs/msw-storybook-addon/releases/tag/v1.8.0) release which should fix this issue, whilst making the addon compatible with Storybook 6 and 7. You can remove the workarounds now.
Thanks for your patience!
